# Using on proxy environment
services:
  demo-app:
    image: tomcat:9.0.95-jre17
    restart: unless-stopped
    volumes:
      - ./war/webapps/ROOT:/usr/local/tomcat/webapps/ROOT

networks:
  default:
    external: true
    name: proxy-cloud
