# Using on proxy environment
services:
  demo-app:
    image: tomcat:9.0.95-jre17
    restart: unless-stopped
    volumes:
      - ./out/artifacts/playlist/playlist.war:/usr/local/tomcat/webapps/ROOT.war

networks:
  default:
    external: true
    name: proxy-cloud
